### ISSUE TITLE
No issue, just some questions

### ISSUE THREAD

**Issue by digitalit** [liam-potter/adonuxt-4#1]
Hi Liam,

What is this for?

Is it to build advanced sites or simple sites?

What is the benefit over using Adonis + Vue in the conventional way?

Thank you.

**Comment by TynesideGroup** [comment]
@digitalit I am very sorry - I have only just spotted this issue!

This template was simply upgrading the existing Adonuxt template (https://github.com/nuxt-community/adonuxt-template) to Adonis 4 as the existing template is still on Adonis 3.x. Users of the existing template may find this beneficial as Adonis 4 offers significant improvements over its predecessor.

It can be used to build simple or advanced sites, but for more advanced sites some people may find it better to split out to separate Adonis (API) and Nuxt (app to consume the API) projects. This template puts both together.

Nuxt has various benefits but I would direct you to their guide for more information: https://nuxtjs.org/guide
